#!/usr/bin/env bun
/**
 * Build script that embeds ask-me.mdc content at compile time
 * by generating a temporary embedded content file
 */
import { readFileSync, writeFileSync, unlinkSync, chmodSync } from 'fs';
import { join } from 'path';

const mdcPath = join(import.meta.dir, '../src/assets/ask-me.mdc');
const mdcContent = readFileSync(mdcPath, 'utf-8');
const embeddedTsPath = join(import.meta.dir, '../src/assets/embedded-content.ts');

// Generate a TypeScript file with the embedded content
const embeddedTs = `// Auto-generated file - DO NOT EDIT
// This file is generated by scripts/build.ts during compilation
export const EMBEDDED_MDC_CONTENT = ${JSON.stringify(mdcContent)};
`;

writeFileSync(embeddedTsPath, embeddedTs, 'utf-8');
console.log('Generated embedded content file');

const args = process.argv.slice(2);
const target = args.find((a) => a.startsWith('--target='))?.split('=')[1];
const outfile = args.find((a) => a.startsWith('--outfile='))?.split('=')[1];

const buildArgs: string[] = ['./src/index.ts', '--compile', '--minify'];

if (target) {
  buildArgs.push(`--target=${target}`);
}

const finalOutfile = outfile || 'dist/ask-me';
buildArgs.push(`--outfile=${finalOutfile}`);

console.log('Building with embedded ask-me.mdc...');
console.log(`Command: bun build ${buildArgs.join(' ')}`);

const proc = Bun.spawn(['bun', 'build', ...buildArgs], {
  stdio: ['inherit', 'inherit', 'inherit'],
});

const exitCode = await proc.exited;

// Clean up generated file
try {
  unlinkSync(embeddedTsPath);
  console.log('Cleaned up generated file');
} catch {
  // Ignore cleanup errors
}

// Post-build: Sign macOS binaries to prevent "damaged" error on other machines
if (exitCode === 0 && target?.includes('darwin')) {
  console.log('Signing macOS binary with ad-hoc signature...');

  try {
    // Ad-hoc sign the binary (no Apple Developer account needed)
    const signProc = Bun.spawn(['codesign', '--sign', '-', '--force', finalOutfile], {
      stdio: ['inherit', 'inherit', 'inherit'],
    });

    const signExitCode = await signProc.exited;

    if (signExitCode === 0) {
      console.log('✓ Binary signed successfully');

      // Also remove quarantine attribute if present
      const xattrProc = Bun.spawn(['xattr', '-c', finalOutfile], {
        stdio: ['ignore', 'ignore', 'ignore'],
      });
      await xattrProc.exited;
    } else {
      console.log('⚠ Signing failed (codesign not available or error)');
      console.log('  On target machine, run: xattr -c ' + finalOutfile);
    }
  } catch {
    // codesign not available (e.g., cross-compiling from non-macOS)
    console.log('⚠ Cannot sign binary (not on macOS)');
    console.log('  On target machine, run: xattr -c ' + finalOutfile);
  }
}

// Post-build: Ensure executable permissions for Unix binaries
if (exitCode === 0 && !target?.includes('windows')) {
  try {
    chmodSync(finalOutfile, 0o755);
    console.log('✓ Set executable permissions');
  } catch {
    // Ignore chmod errors on Windows
  }
}

process.exit(exitCode);
