/**
 * Embedded asset content
 *
 * During development: reads from file system
 * During compiled build: uses generated embedded-content.ts
 */

import { existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

// Try to import the generated embedded content (exists during build)
let embeddedContent: string | null = null;
try {
  // This import will succeed during build (file is generated by scripts/build.ts)
  // and fail during development (file doesn't exist)
  const { EMBEDDED_MDC_CONTENT } = await import('./embedded-content.ts');
  embeddedContent = EMBEDDED_MDC_CONTENT;
} catch {
  // File doesn't exist in development mode
}

/**
 * Get ask-me.mdc content
 * - In compiled binary: returns embedded content from generated file
 * - In development: reads from file system
 */
export function getAskMeMdcContent(): string {
  // Check if embedded content is available (compiled binary)
  if (embeddedContent) {
    return embeddedContent;
  }

  // Development mode: read from file system (same directory as this module)
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  const mdcPath = join(__dirname, 'ask-me.mdc');

  if (existsSync(mdcPath)) {
    return readFileSync(mdcPath, 'utf-8');
  }

  throw new Error(`Cannot find ask-me.mdc at ${mdcPath}. Please reinstall ask-me.`);
}
